/**/*:
  ros__parameters:

    dataset: nvidia_physicalai_av_dataset
    dataset_split: all  # all, train, val, test
    nvidia_filter_countries: Germany  # United States,Germany,France,Italy,Sweden,Spain,Portugal,Greece,Austria,Finland,Croatia,Netherlands,Denmark,Slovenia,Estonia,Slovakia,Belgium,Czechia,Lithuania,Poland,Romania,Luxembourg,Latvia,Hungary,Bulgaria

    publish_ego_data: true
    publish_camera_images: false
    publish_lidar_pointclouds: true
    publish_lidar_object_lists: true
    publish_radar_pointclouds: false