name: docker-ros

on:
  push:
    branches:
      - main
      - benchmark
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@main
        with:
          platform: amd64
          target: dev,run
          enable-slim: false
          base-image: nvcr.io/nvidia/tensorrt:25.03-py3
          ros-distro: jazzy
          rmw-implementation: rmw_zenoh_cpp
          cmake-args: -DCMAKE_BUILD_TYPE=RelWithDebInfo
          command: ros2 launch autoware_lidar_centerpoint lidar_centerpoint.launch.xml
        env:
          TARGET_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=1
