name: docker-ros

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: ika-rwth-aachen/docker-ros@main
        with:
          platform: amd64
          target: dev
          base-image: rwthika/ros2-tensorrt:jazzy
          rmw-implementation: rmw_zenoh_cpp
          command: ros2 launch autoware_lidar_centerpoint lidar_centerpoint.launch.xml
          enable-industrial-ci: false
          enable-slim: false
        env:
          TARGET_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=1
