name: docker-ros

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: ika-rwth-aachen/docker-ros@main
        with:
          platform: amd64
          target: dev
          base-image: rwthika/ros2-tensorrt:jazzy
          rmw-implementation: rmw_zenoh_cpp
          command: ros2 launch autoware_lidar_centerpoint lidar_centerpoint.launch.xml
          enable-industrial-ci: false
          enable-slim: false
        env:
          TARGET_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=1
